### ISSUE TITLE
add i am alive provider

### ISSUE THREAD

**Issue by tibistibi** [tibistibi/mTor#33]
there should be a default i'm alive message provider which will just send an info message that the application is alive. mTor can use this message to make sure the app is still alive.

**Comment by tibistibi** [comment]
should be equal to DiskSpaceMTorMessageProvider and implement a method which will return one simple message with status INFO and content 'i am alive'

**Comment by vyara-bhit** [comment]
Is done

**Comment by vyara-bhit** [comment]
Not tested

**Comment by vyara-bhit** [comment]
Tested, works properly
