### ISSUE TITLE
user should have a alert level

### ISSUE THREAD

**Issue by tibistibi** [tibistibi/mTor#42]
the alert level shoudl be either INFO, WARN, ERROR or none. so the user will receive messages on or above its level. ie a user with INFO will get messages with INFO, WARN and ERROR etc...

**Comment by vyara-bhit** [comment]
It is ready, only for signup is not added the possibility to set the user's alert level, as the following code leads to error (the same code is working in the user's edit part):
signup.jsp
        <s:select list="statusList" key="user.status">/s:select
SignupAction.java
    public List getStatusList() {
        return Status.getAsList();
    }
